### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Juandagarc** [AngularStore/Store#2]
Hacer about

**Comment by C1ndyJS** [comment]
Se realizó la primera estructura básica de texto e imágenes de about, las dimensiones no estoy segura de si concuerdan con el final

**Comment by C1ndyJS** [comment]
Por el momento subí lo estático, hay componentes que añaden un plus muy bonito, si queda tiempo lo hago.

Pero primero queda pendiente verificar las dimensiones con los compañeros que realizaron el diseño y las otras funcionalidades oficiales del contrato.

**Comment by Juandagarc** [comment]
Finalizado
