### ISSUE TITLE
Carrusel, login y register

### ISSUE THREAD

**Issue by Juandagarc** [AngularStore/Store#3]

**Comment by JuanDavidGanan** [comment]
La documentación del código para el login se encuentra en fase final

**Comment by C1ndyJS** [comment]
Santiago Guevara y mi persona vamos a ayudar a realizar el carrusel, ya iniciamos etapa de search resources

**Comment by C1ndyJS** [comment]
Carrusel: ready and completed

**Comment by Juandagarc** [comment]
Finalizado
