### ISSUE TITLE
Eror404

### ISSUE THREAD

**Issue by Juandagarc** [AngularStore/Store#5]

**Comment by santiagoaramillo** [comment]
Nosotros no encargamos del footer y la pagina de error404

**Comment by santiagoaramillo** [comment]
Primero se creo el footer y los contenedores de la informacion que este debia tener por dentro

**Comment by santiagoaramillo** [comment]
Luego le dimos funcionalidad con el TS para que los nombres se fueran creando dinamicamente en el HTML

**Comment by santiagoaramillo** [comment]
Seguido a esto dimos los estilos, corregimos errores al nombrar clases o al usar camelCase, y comentamos todas las lineas del codigo

**Comment by santiagoaramillo** [comment]
Finalmente lo hicimos responsive

**Comment by JulianCorralG** [comment]
![Captura de pantalla 2023-07-16 114743](https://github.com/AngularStore/Store/assets/114829588/a0b38578-e662-4142-99c3-e39387afea6a)
asi quedo el footer finalmente

**Comment by JulianCorralG** [comment]
![image](https://github.com/AngularStore/Store/assets/114829588/7d5c465c-7cc0-4742-8da1-e39c545c9900)
pagina terminada de page not found eroor 404

**Comment by Juandagarc** [comment]
Finalizado
