### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by Juandagarc** [AngularStore/Store#8]

**Comment by pausa11** [comment]
se creó la vista en base al modelo en Adobe xd

**Comment by pausa11** [comment]
Se configuró para que consuma una API local

**Comment by pausa11** [comment]
Se Creo la Funcionalidad de cambiar la imagen con el click

**Comment by pausa11** [comment]
casi terminado el responsive

**Comment by pausa11** [comment]
Se terminó lo responsive, falta que que se agregue el nav y el footer 
![2](https://github.com/AngularStore/Store/assets/129239983/1c0d80e1-8603-4121-9fa5-73762723f4de)

**Comment by Juandagarc** [comment]
Finalizado
