### ISSUE TITLE
Page products

### ISSUE THREAD

**Issue by Juandagarc** [AngularStore/Store#9]

**Comment by Juandagarc** [comment]
Se creo la estética del titulo inicial, falta el resto.

**Comment by Juandagarc** [comment]
Se organizaron los ítems como listas, falta convertirlo a div y centrarlos en 5 columnas

**Comment by jmorales284** [comment]
se organizamos los items y se cambiaron de listas a divs y centrados en 2 filas de 5 columnas

**Comment by jmorales284** [comment]
faltan dibuajar triangulos en la parte derecha

**Comment by jmorales284** [comment]
ya se organizo el consumo de la api

**Comment by Juandagarc** [comment]
Finalizado 😇😘😘😘
